/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zooanimalsystem;

import java.awt.Image;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import zooanimalsystem.ZooKeeper;
/**
 *
 * @author USER-Q
 */
public class ZooDashboard extends javax.swing.JFrame {
AdminDashboard admin;
String fullPath;
    /**
     * Creates new form ZooDashboard
     */
    public ZooDashboard() {
        initComponents();
        String [] Keepers = new String[20] ;
        try{
     for (int i=0;i<admin.zooKeeper.size();i++){
       ZooKeeper e= admin.zooKeeper.get(i);
       Keepers[i]=  e.getname();
               }
        }catch(java.lang.ArrayIndexOutOfBoundsException e){
        System.out.println("catch it");
        }
    ComboBoxModel<String> aModel = new DefaultComboBoxModel(Keepers);
        jComboBox2.setModel(aModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        textid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textname = new javax.swing.JTextField();
        textpalce = new javax.swing.JTextField();
        textvacc = new javax.swing.JTextField();
        lableimage = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textbarth1 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(31, 29, 43));

        jLabel5.setBackground(new java.awt.Color(37, 40, 54));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("ADD NEW ANIMAL");

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setAlignmentX(1.0F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 110));

        jPanel2.setBackground(new java.awt.Color(31, 29, 43));

        textid.setBackground(new java.awt.Color(45, 48, 62));
        textid.setForeground(new java.awt.Color(204, 204, 204));
        textid.setBorder(null);
        textid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID of Animal:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Birthday  of Animal:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name of Animal:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("The Vaccinations");

        textname.setBackground(new java.awt.Color(45, 48, 62));
        textname.setForeground(new java.awt.Color(204, 204, 204));
        textname.setBorder(null);
        textname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnameActionPerformed(evt);
            }
        });

        textpalce.setBackground(new java.awt.Color(45, 48, 62));
        textpalce.setForeground(new java.awt.Color(204, 204, 204));
        textpalce.setBorder(null);
        textpalce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpalceActionPerformed(evt);
            }
        });

        textvacc.setBackground(new java.awt.Color(45, 48, 62));
        textvacc.setForeground(new java.awt.Color(204, 204, 204));
        textvacc.setBorder(null);
        textvacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textvaccActionPerformed(evt);
            }
        });

        lableimage.setBackground(new java.awt.Color(45, 48, 62));
        lableimage.setForeground(new java.awt.Color(45, 48, 62));
        lableimage.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 48, 62)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(31, 29, 43))); // NOI18N

        jButton1.setBackground(new java.awt.Color(45, 48, 62));
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Load Image");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 48, 62)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(31, 29, 43));
        jButton10.setForeground(new java.awt.Color(234, 124, 105));
        jButton10.setText("Add new Animal");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 48, 62)));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Animal type");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Place of Birth:");

        textbarth1.setBackground(new java.awt.Color(45, 48, 62));
        textbarth1.setForeground(new java.awt.Color(204, 204, 204));
        textbarth1.setText("20/02/2020");
        textbarth1.setBorder(null);
        textbarth1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbarth1ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(31, 29, 43));
        jButton12.setForeground(new java.awt.Color(234, 124, 105));
        jButton12.setText("Back");
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 48, 62)));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(31, 29, 43));
        jComboBox1.setForeground(new java.awt.Color(204, 204, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dog", "Duck", "Eagle", "Elephant", "Panda", "Lion", "Parrot", "Penguin" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 48, 62)));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Charge Keeper");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textname)
                            .addComponent(textbarth1)
                            .addComponent(textpalce)
                            .addComponent(textvacc)
                            .addComponent(textid, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, 0, 203, Short.MAX_VALUE)
                            .addComponent(lableimage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textbarth1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textpalce, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textvacc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lableimage, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 103, 540, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidActionPerformed

    private void textnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnameActionPerformed

    private void textpalceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpalceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpalceActionPerformed

    private void textvaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textvaccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textvaccActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter nef = new FileNameExtensionFilter("IMAGES","pmg","jpg","jpeg");
        fileChooser.addChoosableFileFilter(nef);
        fileChooser.setAcceptAllFileFilterUsed(false);

        int option = fileChooser.showOpenDialog(null);
        if(option == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            fullPath = file.getAbsolutePath();
            JOptionPane.showMessageDialog(null,fullPath);

            //  label.setText("File Selected: " + file.getName());
            ImageIcon newimage= new ImageIcon(fullPath);
            Image image =newimage.getImage().getScaledInstance(lableimage.getWidth(), lableimage.getHeight(), Image.SCALE_SMOOTH);
            lableimage.setIcon(new ImageIcon(image));
            //   label.setIcon(new javax.swing.ImageIcon(getClass().getResource(fullPath))); // NOI18N
        }else{
            lableimage.setText("Open command canceled");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
String name = textname.getText();
int id = Integer.parseInt(textid.getText());
   String birthDate=textbarth1.getText();
       SimpleDateFormat date=new SimpleDateFormat("dd/MM/yyyy");  
    try {
        date .parse(birthDate);
    } catch (ParseException ex) {
        Logger.getLogger(ZooDashboard.class.getName()).log(Level.SEVERE, null, ex);
    }
            
           String type = (String) jComboBox1.getSelectedItem();
           String keepername = (String) jComboBox2.getSelectedItem();
           System.out.println("type is "+type);
    String vaccination = textvacc.getText();
        String place =textpalce.getText();
        int keeperID=0;
        
    for (int i=0;i<admin.zooKeeper.size();i++){
 if(keepername == admin.zooKeeper.get(i).getname()){
     ZooKeeper e= admin.zooKeeper.get(i);
 keeperID=e.getZooID();
 }
 }
        
    if (type == "Dog"){ 
        Dog Dog = new Dog (id,name,place,fullPath,type,vaccination,birthDate,keeperID);
        
          AdminDashboard.get_data_animal(Dog);
    }
    
    if (type == "Duck"){
        Duck Duck = new Duck (id,name,place,fullPath,type,vaccination,birthDate,keeperID);
           AdminDashboard.get_data_animal(Duck);
    }
    
    if (type == "Eagle"){
        Eagle Eagle = new Eagle (id,name,place,fullPath,type,vaccination,birthDate,keeperID);
         AdminDashboard.get_data_animal(Eagle);
    }
    
    if (type == "Elephant"){
     Elephant Elephant = new Elephant(id,name,place,fullPath,type,vaccination,birthDate,keeperID);
            AdminDashboard.get_data_animal(Elephant);            
    }
 
     if (type == "Panda"){
        Panda Panda = new Panda (id,name,place,fullPath,type,vaccination,birthDate,keeperID);
            AdminDashboard.get_data_animal(Panda);
     }
     if (type == "Lion"){
       Lion Lion = new Lion(id,name,place,fullPath,type,vaccination,birthDate,keeperID);
        AdminDashboard.get_data_animal(Lion);
     }
      if (type == "Parrot"){
            Parrot Parrot = new Parrot(id,name,place,fullPath,type,vaccination,birthDate,keeperID);
       AdminDashboard.get_data_animal(Parrot);
      }
     if (type == "Penguin")
     {  Penguin Penguin = new Penguin(id,name,place,fullPath,type,vaccination,birthDate,keeperID);
       AdminDashboard.get_data_animal(Penguin);
     }
     this.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void textbarth1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbarth1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textbarth1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZooDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZooDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZooDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZooDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZooDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lableimage;
    private javax.swing.JTextField textbarth1;
    private javax.swing.JTextField textid;
    private javax.swing.JTextField textname;
    private javax.swing.JTextField textpalce;
    private javax.swing.JTextField textvacc;
    // End of variables declaration//GEN-END:variables
}
